services:
  - type: web
    name: dashboard-saude
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_VERSION
        value: 18
    disk:
      name: data
      mountPath: /data
      sizeGB: 1
  - type: web
    name: n8n
    env: docker
    plan: free
    dockerCommand: docker run -p 5678:5678 n8nio/n8n
    envVars:
      - key: N8N_HOST
        value: 0.0.0.0
      - key: N8N_PORT
        value: 5678